version: "3.7"

services:
  auto-rewards:
    build:
      context: .
    environment:
      EXPLORER_API_URL: http://176.9.78.13:9050
      TOKEN: NOAH
      SEED_PHRASE: SEED
      BASE_COIN: NOAH
      NODE_API_URL: http://176.9.116.72:8841
      TIME_ZONE: Europe/Moscow
      TIME_START: "13:00"